//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db2Source.DataSet {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Db2srcDataSet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Db2srcDataSet() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Db2Source.DataSet.Db2srcDataSet", typeof(Db2srcDataSet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   日付書式(表示) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日時書式(表示) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ {0} が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessagePropertyNotFound {
            get {
                return ResourceManager.GetString("MessagePropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行に影響を与えました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageRowsAffected {
            get {
                return ResourceManager.GetString("MessageRowsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行文字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewLineRule {
            get {
                return ResourceManager.GetString("NewLineRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付書式(入力) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParseDateFormat {
            get {
                return ResourceManager.GetString("ParseDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日時書式(入力) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParseDateTimeFormats {
            get {
                return ResourceManager.GetString("ParseDateTimeFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時刻書式(入力) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParseTimeFormats {
            get {
                return ResourceManager.GetString("ParseTimeFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [エラー]  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefixError {
            get {
                return ResourceManager.GetString("PrefixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時刻書式(表示) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
    }
}
