//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db2Source.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Db2Source.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   再実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonRedo_Tooltip {
            get {
                return ResourceManager.GetString("ButtonRedo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FindNextCommand_Name {
            get {
                return ResourceManager.GetString("FindNextCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FindPreviousCommand_Name {
            get {
                return ResourceManager.GetString("FindPreviousCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Confirm {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Drop {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Error {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Info {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Quit {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Result {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxCaption_Succeed {
            get {
                return ResourceManager.GetString("MessageBoxCaption_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続成功 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxText_Connected {
            get {
                return ResourceManager.GetString("MessageBoxText_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了します。よろしいですか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxText_Quit {
            get {
                return ResourceManager.GetString("MessageBoxText_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい接続... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewConnectionTitle {
            get {
                return ResourceManager.GetString("NewConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用方法:
        ///DB2Src.net [OPTIONS]... [Directory]
        ///
        ///一般的なオプション:
        ///  -?, --help		このヘルプを表示し、終了します
        ///
        ///接続オプション
        ///  -d, --dbname=DATABASE	データベース名
        ///  -h, --host=HOSTNAME	データベースサーバのホストまたはソケットディレクトリ
        ///  -p, --port=PORT		データベースサーバのポート番号
        ///  -U, --username=NAME	指定したデータベースユーザで接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
